name: Deploy
on:
  push:
    branches: ['feat/schedule-join']
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Push to forked repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: wooseung0124
          destination-repository-name: swineunshigan-user-frontend
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: feat/schedule-join
